name: Terragrunt Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      work-folder:
        required: true
        type: string
      terragrunt_action:
        required: true
        type: string

jobs:
  infrastructure:
    name: '${{ github.event.inputs.work-folder }}'
    environment: '${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true # This environment variable tells the backend to use AzureAD auth rather than trying a create a key. It means we can limit the permissions applied to the storage account and container to least priviledge: https://developer.hashicorp.com/terragrunt/language/settings/backends/azurerm#use_azuread_auth

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    - if: github.event.inputs.terragrunt_action == 'plan'
      name: Terragrunt Plan
      run: |
        echo "this seems to be working..."
        echo  "${{ github.event.inputs.environment }}"
        echo  "${{ github.event.inputs.terragrunt_action }}"

    # Run Terragrunt apply only if the apply is specified as a Terragrunt action
    - if: github.event.inputs.terragrunt_action == 'apply'
      name: Terragrunt Apply
      run: |
        set -eu

        if [[ "${{ github.event.inputs.work-folder }}" == 'all' ]]
        then
          terragrunt run-all apply --terragrunt-non-interactive --auto-approve
        else
          cd "${{ github.event.inputs.work-folder }}" || { echo "Failed to change directory to '${{ github.event.inputs.work-folder }}'"; exit 1; }
          terragrunt apply --terragrunt-non-interactive --auto-approve
        fi
      working-directory: 'landing-zones/mitosis/${{ github.event.inputs.environment }}'
